version: "3.9"
services:
  web:
    image: myapp:1.0.0
    container_name: django_app
    command: >
      sh -c "python manage.py migrate &&
      gunicorn HuellaVial.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    ports:
      - "8000:8000"
    env_file: 
      - .env
    volumes:
      - static_volume:/code/staticfiles
    depends_on:
    - db
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: huellavial_db
      POSTGRES_USER: angelcruz
      POSTGRES_PASSWORD: 7deenerode2004
    volumes:
      - ./db_data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume: