# Generated by Django 5.1.7 on 2025-04-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_projects_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="creation_date",
            field=models.DateField(),
        ),
    ]
