# Generated by Django 5.1.7 on 2025-04-04 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_projects_creation_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="projects",
            name="creation_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "id_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.projects",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=100)),
                (
                    "id_phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.phase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="subresource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "id_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.resource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intensity",
                    models.IntegerField(
                        choices=[
                            (1, "Minima"),
                            (2, "Moderada"),
                            (3, "Alta"),
                            (5, "Muy Alta"),
                        ]
                    ),
                ),
                (
                    "importance",
                    models.IntegerField(
                        choices=[
                            (1, "Minima"),
                            (2, "Moderada"),
                            (3, "Alta"),
                            (5, "Muy Alta"),
                        ]
                    ),
                ),
                (
                    "extension",
                    models.IntegerField(
                        choices=[
                            (1, "Minima"),
                            (2, "Moderada"),
                            (3, "Alta"),
                            (5, "Muy Alta"),
                        ]
                    ),
                ),
                (
                    "persistence",
                    models.IntegerField(
                        choices=[
                            (1, "Minima"),
                            (2, "Moderada"),
                            (3, "Alta"),
                            (5, "Muy Alta"),
                        ]
                    ),
                ),
                (
                    "reversibility",
                    models.IntegerField(
                        choices=[
                            (1, "Minima"),
                            (2, "Moderada"),
                            (3, "Alta"),
                            (5, "Muy Alta"),
                        ]
                    ),
                ),
                ("description", models.CharField(max_length=50)),
                (
                    "id_phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.phase",
                    ),
                ),
                (
                    "id_subresource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.subresource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="impact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observation", models.CharField(max_length=30)),
                (
                    "id_operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.operation",
                    ),
                ),
                (
                    "id_subresource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.subresource",
                    ),
                ),
            ],
        ),
    ]
