# Generated by Django 5.1.7 on 2025-04-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_resource_alter_projects_creation_date_phase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subresource",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
