# Generated by Django 5.1.7 on 2025-04-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_subresource_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impact",
            name="observation",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="rating",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
