# Generated by Django 5.1.7 on 2025-04-05 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_alter_impact_observation_alter_rating_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phase",
            name="id_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phases",
                to="dashboard.projects",
            ),
        ),
    ]
