# Generated by Django 5.1.7 on 2025-04-06 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_phase_id_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="id_phase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="dashboard.phase",
            ),
        ),
        migrations.AlterField(
            model_name="subresource",
            name="id_resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subresources",
                to="dashboard.resource",
            ),
        ),
    ]
