# Generated by Django 5.1.7 on 2025-04-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_alter_operation_id_phase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="impact",
            name="is_marked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="impact",
            name="observation",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="impact",
            unique_together={("id_operation", "id_subresource")},
        ),
    ]
