# Generated by Django 5.1.7 on 2025-04-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_impact_is_marked_alter_impact_observation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="description",
            field=models.CharField(default="NA", max_length=100),
        ),
        migrations.AlterField(
            model_name="rating",
            name="extension",
            field=models.IntegerField(
                choices=[(1, "Minima"), (2, "Moderada"), (3, "Alta"), (5, "Muy Alta")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="importance",
            field=models.IntegerField(
                choices=[(1, "Minima"), (2, "Moderada"), (3, "Alta"), (5, "Muy Alta")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="intensity",
            field=models.IntegerField(
                choices=[(1, "Minima"), (2, "Moderada"), (3, "Alta"), (5, "Muy Alta")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="persistence",
            field=models.IntegerField(
                choices=[(1, "Minima"), (2, "Moderada"), (3, "Alta"), (5, "Muy Alta")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="reversibility",
            field=models.IntegerField(
                choices=[(1, "Minima"), (2, "Moderada"), (3, "Alta"), (5, "Muy Alta")],
                default=1,
            ),
        ),
    ]
