# Generated by Django 5.1.7 on 2025-04-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0011_alter_operation_description_alter_rating_extension_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="description",
            field=models.CharField(default="NA", max_length=200),
        ),
    ]
