# Generated by Django 5.1.7 on 2025-04-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_alter_rating_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="phase",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="resource",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
