# Generated by Django 5.1.7 on 2025-04-29 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_alter_operation_name_alter_phase_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="id_phase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="dashboard.phase",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="id_subresource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subresources",
                to="dashboard.subresource",
            ),
        ),
    ]
