# Generated by Django 5.1.7 on 2025-04-29 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_alter_rating_id_phase_alter_rating_id_subresource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impact",
            name="id_operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="impacts",
                to="dashboard.operation",
            ),
        ),
        migrations.AlterField(
            model_name="impact",
            name="id_subresource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="impacts",
                to="dashboard.subresource",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="id_subresource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.subresource"
            ),
        ),
    ]
