# Generated by Django 5.1.7 on 2025-05-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_alter_impact_id_operation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="impact",
            name="observation",
        ),
        migrations.RemoveField(
            model_name="operation",
            name="description",
        ),
        migrations.CreateModel(
            name="reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=1000)),
                (
                    "id_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="dashboard.projects",
                    ),
                ),
            ],
        ),
    ]
