# Generated by Django 5.1.7 on 2025-05-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_remove_impact_observation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reports",
            name="content",
            field=models.CharField(max_length=2000),
        ),
    ]
