# Generated by Django 5.1.7 on 2025-05-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_alter_reports_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reports",
            name="content",
            field=models.CharField(),
        ),
    ]
